from limbook_api.errors.auth_error import AuthError
